### ISSUE TITLE
Show popover if mouse is over element

### ISSUE THREAD

**Issue by pchomik** [pleerock/ng2-popover#1]
Hello,

In current implementation popover is working when element is clicked. Is it possible to add support for hover or mouseover action ?

**Comment by pleerock** [comment]
I'll add support today

**Comment by pchomik** [comment]
Thanks.

**Comment by pleerock** [comment]
btw do you really need a popover and not a [tooltip](https://github.com/pleerock/ng2-tooltip)?

**Comment by pleerock** [comment]
released in **0.0.2**. Use `popoverOnHover` and `popoverCloseOnMouseOutside` options. More info in readme and sample.

**Comment by pchomik** [comment]
Thanks. Your change is working as expected.
