### ISSUE TITLE
Suggestion: add usage example as Plunker

### ISSUE THREAD

**Issue by markpritchett** [pleerock/ng2-popover#20]
Hello, have you considered adding a plunker showing an example of how to use this component?  It might be a good starting point for people wanting to to play around with this component.  It could also be used as a basis for reporting any issues.

I've created an example plunker based on your example in: https://github.com/pleerock/ng2-popover/tree/master/sample/sample1-simple-usage

Here's the plunker - http://plnkr.co/edit/eU5x2idKcMFzA6OAqHm6?p=preview

**Comment by pleerock** [comment]
thank you very much for this demo in plunker. I wanted to do it (and for my other components) but havent time yet to do it. Thank you for your help
