### ISSUE TITLE
Demo Plunker is not working

### ISSUE THREAD

**Issue by Gauravkr** [pleerock/ng2-popover#21]
Link : http://plnkr.co/edit/eU5x2idKcMFzA6OAqHm6?p=preview

Error : zone.js@0.6.17:484 Unhandled Promise rejection: Zone.assertZonePatched is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Zone.assertZonePatched is not a function(…) TypeError: Zone.assertZonePatched is not a function

**Comment by pleerock** [comment]
checkout [new one](http://plnkr.co/edit/tmGQ43m3OGhn8uoAYWua?p=preview)
