### ISSUE TITLE
Arrow is not visible

### ISSUE THREAD

**Issue by timefordroids** [pleerock/ng2-popover#27]
Hi, 
I have a problem with the arrow. It is not visible in my app.
![pipelines - mozilla firefox 2016-10-05 18 26 13](https://cloud.githubusercontent.com/assets/710200/19142519/9f6fc2aa-8ba6-11e6-997a-924f2a2d88ec.png)
As I understand the cause is in different class names ('popover-arrow' in bootstrap and 'arrow' in ng2-bootstrap)
![pipelines - mozilla firefox 2016-10-05 18 24 17](https://cloud.githubusercontent.com/assets/710200/19142552/dce9f182-8ba6-11e6-9acc-2be07f391885.png)
I'm using:
"bootstrap": "4.0.0-alpha.4",
"ng-popover" 0.0.9,
"ng2-bootstrap": "1.1.5"

**Comment by joehansen** [comment]
Same Problem.

"ng2-bootstrap": "1.1.11",
 "ng2-popover": "0.0.10",
"bootstrap": "4.0.0-alpha.3",

**Comment by pleerock** [comment]
maybe you have this problem because both of you are using bootstrap 4? This library works only with bootstrap 3.

**Comment by timefordroids** [comment]
Oh, sure. Lets close the issue.

**Comment by BenDevelopment** [comment]
I'm sorry to reopen this issue but it will be easy to update to Bootstrap v4. Do you plan to do it or do you want to stay in v3 version?
I can make a pull request if you want.

**Comment by pleerock** [comment]
@BenDevelopment I'll think about v4 once it will be released. Until that if its possible to make this component work with both v3 and v4 then it would be great if you create a PR with this feature implemented.
