### ISSUE TITLE
Not AOT compatible

### ISSUE THREAD

**Issue by aaronleeucla** [pleerock/ng2-popover#29]
using Angular-CLI 1.0.0beta-17, `ng build --target=production`, no problem.
But with `--aot=true`, this error appears: 

`Unexpected value 'PopoverModule' exported by the module 'MySharedModule'`

Same thing happens when trying to import it in an @NgModule().

A few other libraries are running into this issue as well now that aot support is added. For example, https://github.com/valor-software/ng2-dragula/issues/443

valor-software's ng2-bootstrap library seems to have overcame this issue.

**Comment by aaronleeucla** [comment]
I forked it in trying to figure out a solution, and got it working.

**Comment by pleerock** [comment]
can you create a PR from your fork?

**Comment by aaronleeucla** [comment]
I'm hesitant because it's a bit of a hack; it's not quite built and exported through your gulp workflow. For example, the fork checks in a /dist folder and package.json points to that as the main import.

I was experimenting using these instructions: https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.eh4hesrmr.

**Comment by GuskiS** [comment]
Any progress?

**Comment by goleary** [comment]
the other option is you just include src folder in your own project and import from there

**Comment by pleerock** [comment]
released in `0.0.13`, thanks @am-hs
