### ISSUE TITLE
Timeout based dismissal feature request!!

### ISSUE THREAD

**Issue by cackharot** [pleerock/ng2-popover#3]
Thanks for sharing this amazing component!

Would be great if you could add a timeout variable to dismiss the popover automatically.

Example: `<div popover="some content" popoverDismissTimeout="10"></div>`

`popoverDismissTimeout="{{seconds}}"` -- destroys the component in 10 seconds -- default (-1), do not destroy.

**Comment by pleerock** [comment]
looks like nice feature to have

**Comment by pleerock** [comment]
added in **0.0.6** . Star this component and share with others ;)
