### ISSUE TITLE
Popover position is incorrect

### ISSUE THREAD

**Issue by ish2028** [pleerock/ng2-popover#35]
The position of the popover is in the wrong location.  Attached is a screen shot.  I am using Bootstraps navbar at the top.  Any help would be appreciated.
![screen shot 2016-11-14 at 11 11 18 am](https://cloud.githubusercontent.com/assets/20907337/20278911/54b9488e-aa5b-11e6-8644-6a55c37fd123.png)

**Comment by pleerock** [comment]
its easy to break popover location by applying some specific css on your site. try to use popover without any your own css. if you think there is a bug with how popover positioning itself then please provide more specific information.
