### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by JoBlob** [pleerock/ng2-popover#36]
`angular2-webpack@1.0.0 J:\repositories\NG2
+-- UNMET PEER DEPENDENCY @angular/common@2.1.2
+-- UNMET PEER DEPENDENCY @angular/core@2.1.2
+-- UNMET PEER DEPENDENCY @angular/forms@2.1.2
+-- UNMET PEER DEPENDENCY @angular/http@2.1.2
`-- ng2-popover@0.0.11  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN angular2localization@1.2.0 requires a peer of @angular/common@^2.2.0 but none was installed.
npm WARN angular2localization@1.2.0 requires a peer of @angular/core@^2.2.0 but none was installed.
npm WARN angular2localization@1.2.0 requires a peer of @angular/forms@^2.2.0 but none was `installed.`
npm WARN angular2localization@1.2.0 requires a peer of @angular/http@^2.2.0 but none was installed.
npm WARN angular2-webpack@1.0.0 No repository field.
npm WARN angular2-webpack@1.0.0 No license field.
`

**Comment by pleerock** [comment]
it does not look like a popover issue. Make sure all your dependencies are correct.
