### ISSUE TITLE
"//# sourceMappingURL" text in *.js debugging issue.

### ISSUE THREAD

**Issue by l2thet** [pleerock/ng2-popover#4]
The *.js files in the npm package all have the //# sourceMappingURL line, this is causing problems with Electron debugging. When I attempt to set a break point it will jump to a non-existing file named what the soureMappingURL is set to.

**Comment by pleerock** [comment]
source maps are being automatically generated by typescript compiler. `@angular` has the same  //# sourceMappingURL lines in its .js files, and its how it should be. Do you have problems with angular source maps too?

**Comment by l2thet** [comment]
No I don't have problems with the angular source maps because angular includes a "src" folder that matches the mapping files referenced in the *.js files.

Sorry for the late response, been a busy few days, will get back with the other issues I posted at some point in the next few days.

**Comment by pleerock** [comment]
fixed in 0.0.7
